package com.tobiasfried.brewkeeper.data;

import java.time.LocalDate;
import java.util.List;

import androidx.room.Entity;
import androidx.room.Ignore;

import com.tobiasfried.brewkeeper.constants.*;
import static com.tobiasfried.brewkeeper.data.Brew.TABLE_NAME;

@Entity(tableName = TABLE_NAME)
public class Brew extends Recipe {

    public static final String TABLE_NAME = "brews";
    private static final String LOG_TAG = Brew.class.getSimpleName();

    // MEMBER FIELDS

    private LocalDate primaryStartDate;

    private LocalDate secondaryStartDate;

    private LocalDate endDate;

    private Stage stage;

    private boolean isRunning;


    // CONSTRUCTORS

    /**
     * Constructor for programmatic use
     *
     * @param name                     Brew name
     * @param tea                      Tea {@link Ingredient}
     * @param teaAmount                in grams
     * @param primarySweetener         Sweetener {@link Ingredient}
     * @param primarySweetenerAmount   in grams
     * @param secondarySweetener       Sweetener {@link Ingredient}
     * @param secondarySweetenerAmount in grams
     * @param ingredients              ArrayList<{@link Ingredient}>
     * @param primaryStartDate         {@link LocalDate}
     * @param secondaryStartDate       {@link LocalDate}
     * @param endDate                  {@link LocalDate}
     * @param stage                    Stage {@link Stage}
     * @param isRunning                boolean
     */
    public Brew(String name, Ingredient tea, int teaAmount,
                int primarySweetener, int primarySweetenerAmount,
                int secondarySweetener, int secondarySweetenerAmount,
                List<Ingredient> ingredients,
                LocalDate primaryStartDate,
                LocalDate secondaryStartDate,
                LocalDate endDate,
                Stage stage, boolean isRunning) {
        super(name, tea, teaAmount,
                primarySweetener, primarySweetenerAmount,
                secondarySweetener, secondarySweetenerAmount,
                ingredients);
        this.primaryStartDate = primaryStartDate;
        this.secondaryStartDate = secondaryStartDate;
        this.endDate = endDate;
        this.stage = stage;
        this.isRunning = isRunning;
    }

    /**
     * Constructor for Room use only
     *
     * @param id                       Autogenerated
     * @param name                     Brew name
     * @param teaId                    references ingredient_id from ingredients table
     * @param teaAmount                in grams
     * @param primarySweetener       references ingredient_id from ingredients table
     * @param primarySweetenerAmount   in grams
     * @param secondarySweetener     references ingredient_id from ingredients table
     * @param secondarySweetenerAmount in grams
     * @param ingredientOneId          references ingredient_id from ingredients table
     * @param ingredientTwoId          references ingredient_id from ingredients table
     * @param ingredientThreeId        references ingredient_id from ingredients table
     * @param primaryStartDate         stored as a long via TypeConverter
     * @param secondaryStartDate       stored as a long via TypeConverter
     * @param endDate                  stored as a long via TypeConverter
     * @param stage                    stored as an int via TypeConverter
     * @param isRunning                boolean
     */
    public Brew(long id, String name, long teaId, int teaAmount, int primarySweetener,
                int primarySweetenerAmount, int secondarySweetener,
                int secondarySweetenerAmount, long ingredientOneId,
                long ingredientTwoId, long ingredientThreeId,
                LocalDate primaryStartDate,
                LocalDate secondaryStartDate,
                LocalDate endDate,
                Stage stage, boolean isRunning) {
        super(id, name, teaId, teaAmount,
                primarySweetener, primarySweetenerAmount,
                secondarySweetener, secondarySweetenerAmount,
                ingredientOneId, ingredientTwoId, ingredientThreeId);
        this.primaryStartDate = primaryStartDate;
        this.secondaryStartDate = secondaryStartDate;
        this.endDate = endDate;
        this.stage = stage;
        this.isRunning = isRunning;
    }

    /**
     * Empty constructor for editor activity
     */
    @Ignore
    public Brew() {
        super();
    }

    // GETTERS

    public LocalDate getPrimaryStartDate() {
        return primaryStartDate;
    }

    public LocalDate getSecondaryStartDate() {
        return secondaryStartDate;
    }

    public LocalDate getEndDate() {
        return this.endDate;
    }

    public Stage getStage() {
        return stage;
    }

    public boolean isRunning() {
        return isRunning;
    }


    // SETTERS

    public void setPrimaryStartDate(LocalDate primaryStartDate) {
        this.primaryStartDate = primaryStartDate;
    }

    public void setSecondaryStartDate(LocalDate secondaryStartDate) {
        this.secondaryStartDate = secondaryStartDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public void setStage(Stage stage) {
        this.stage = stage;
    }

    public void setRunning(boolean running) {
        isRunning = running;
    }

}
