package com.tobiasfried.brewkeeper.data;

import java.time.ZonedDateTime;
import java.util.List;

import androidx.room.Entity;
import com.tobiasfried.brewkeeper.constants.*;
import static com.tobiasfried.brewkeeper.data.Brew.TABLE_NAME;

@Entity(tableName = TABLE_NAME)
public class Brew extends Recipe {

    public static final String TABLE_NAME = "brews";
    private static final String LOG_TAG = Brew.class.getSimpleName();

    // MEMBER FIELDS

    private ZonedDateTime primaryStartDate;

    private ZonedDateTime secondaryStartDate;

    private ZonedDateTime endDate;

    private Stage stage;

    private boolean isRunning;


    // CONSTRUCTORS

    /**
     * Constructor for programmatic use
     *
     * @param name                     Brew name
     * @param tea                      Tea {@link Ingredient}
     * @param teaAmount                in grams
     * @param primarySweetener         Sweetener {@link Ingredient}
     * @param primarySweetenerAmount   in grams
     * @param secondarySweetener       Sweetener {@link Ingredient}
     * @param secondarySweetenerAmount in grams
     * @param ingredients              ArrayList<{@link Ingredient}>
     * @param primaryStartDate         {@link ZonedDateTime}
     * @param secondaryStartDate       {@link ZonedDateTime}
     * @param endDate                  {@link ZonedDateTime}
     * @param stage                    Stage {@link Stage}
     * @param isRunning                boolean
     */
    public Brew(String name, Ingredient tea, int teaAmount,
                int primarySweetener, int primarySweetenerAmount,
                int secondarySweetener, int secondarySweetenerAmount,
                List<Ingredient> ingredients,
                ZonedDateTime primaryStartDate,
                ZonedDateTime secondaryStartDate,
                ZonedDateTime endDate,
                Stage stage, boolean isRunning) {
        super(name, tea, teaAmount,
                primarySweetener, primarySweetenerAmount,
                secondarySweetener, secondarySweetenerAmount,
                ingredients);
        this.primaryStartDate = primaryStartDate;
        this.secondaryStartDate = secondaryStartDate;
        this.endDate = endDate;
        this.stage = stage;
        this.isRunning = isRunning;
    }


    /**
     * Constructor for Room use only
     *
     * @param id                       Autogenerated
     * @param name                     Brew name
     * @param teaId                    references ingredient_id from ingredients table
     * @param teaAmount                in grams
     * @param primarySweetener       references ingredient_id from ingredients table
     * @param primarySweetenerAmount   in grams
     * @param secondarySweetener     references ingredient_id from ingredients table
     * @param secondarySweetenerAmount in grams
     * @param ingredientOneId          references ingredient_id from ingredients table
     * @param ingredientTwoId          references ingredient_id from ingredients table
     * @param ingredientThreeId        references ingredient_id from ingredients table
     * @param primaryStartDate         stored as a long via TypeConverter
     * @param secondaryStartDate       stored as a long via TypeConverter
     * @param endDate                  stored as a long via TypeConverter
     * @param stage                    stored as an int via TypeConverter
     * @param isRunning                boolean
     */
    public Brew(int id, String name, long teaId, int teaAmount, int primarySweetener,
                int primarySweetenerAmount, int secondarySweetener,
                int secondarySweetenerAmount, long ingredientOneId,
                long ingredientTwoId, long ingredientThreeId,
                ZonedDateTime primaryStartDate,
                ZonedDateTime secondaryStartDate,
                ZonedDateTime endDate,
                Stage stage, boolean isRunning) {
        super(id, name, teaId, teaAmount,
                primarySweetener, primarySweetenerAmount,
                secondarySweetener, secondarySweetenerAmount,
                ingredientOneId, ingredientTwoId, ingredientThreeId);
        this.primaryStartDate = primaryStartDate;
        this.secondaryStartDate = secondaryStartDate;
        this.endDate = endDate;
        this.stage = stage;
        this.isRunning = isRunning;
    }

    // GETTERS

    public ZonedDateTime getPrimaryStartDate() {
        return primaryStartDate;
    }

    public ZonedDateTime getSecondaryStartDate() {
        return secondaryStartDate;
    }

    public ZonedDateTime getEndDate() {
        return this.endDate;
    }

    public Stage getStage() {
        return stage;
    }

    public boolean isRunning() {
        return isRunning;
    }


    // SETTERS

    public void setPrimaryStartDate(ZonedDateTime primaryStartDate) {
        this.primaryStartDate = primaryStartDate;
    }

    public void setSecondaryStartDate(ZonedDateTime secondaryStartDate) {
        this.secondaryStartDate = secondaryStartDate;
    }

    public void setEndDate(ZonedDateTime endDate) {
        this.endDate = endDate;
    }

    public void setStage(Stage stage) {
        this.stage = stage;
    }

    public void setRunning(boolean running) {
        isRunning = running;
    }

}
